---

  - name: install chrony
    yum: 
      name: ['chrony', 'augeas']
      state: installed

 
  - name: remove ntp
    yum: 
      name: ntp
      state: absent

  - name: change chrony config
    command: augtool set /files/etc/chrony.conf/server[1] {{ ntpserver }}

  - name: change chrony config
    command: augtool set /files/etc/chrony.conf/server[1]/iburst

  - name: start chrony
    service:
      name: chronyd
      state: restarted
      enabled: true
